#!/bin/bash

current_dir=$(pwd)
parent_dir=$(dirname "$current_dir")

find "$current_dir" -maxdepth 1 -type f -name "*.html" -exec cp -u {} "$parent_dir" \;

echo "HTML files copied successfully (if they didn't exist or were newer)."

